import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Brand from "@/app/components/Brand";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";
import NavLink from "@/app/components/NavLink";
import NavMenu from "@/app/components/NavMenu";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Header>
            <Brand />
            <NavMenu>
              <NavLink href="/">Home</NavLink>
              <NavLink href="/users">Users</NavLink>
            </NavMenu>
          </Header>

          <main className="mx-auto w-full max-w-5xl flex-1 px-6 py-8">
            {children}
          </main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
